### ISSUE TITLE
 Cannot connect to new Peer after disconnecting from server

### ISSUE THREAD

**Issue by ilayadivya** [hoaphantn7604/react-native-webrtc-simple#5]
[Error: Cannot connect to new Peer after disconnecting from server.]
 ERROR  TypeError: undefined is not an object (evaluating 'peerConn.on')

**Comment by hoaphantn7604** [comment]
I'm working on it.

**Comment by ilayadivya** [comment]
Thank you

**Comment by hoaphantn7604** [comment]
I have resolved your problem, will release a new version tomorrow.

**Comment by ilayadivya** [comment]
Thank you , disconnected automatically  after connecting 2 or 3 minutes ,
reject call null . Returned

**Comment by hoaphantn7604** [comment]
When the device turns off the screen, the connection is lost.
You must refresh the connection using this "WebrtcSimple.refresh()" method when returning the application.
Please install later version 1.1.2.
