### ISSUE TITLE
disconnected automatically  after connecting 1 or 3 minutes

### ISSUE THREAD

**Issue by ilayadivya** [hoaphantn7604/react-native-webrtc-simple#6]
disconnected automatically  after connecting 1 or 2 minutes , Returned reject call null , no error showing

**Comment by hoaphantn7604** [comment]
When the device turns off the screen, the connection is lost.
You must refresh the connection using this "WebrtcSimple.refresh()" method when returning the application.
Please install later version 1.1.2.

**Comment by ilayadivya** [comment]
AppState.addEventListener("change", this._handleAppStateChange.bind(this))

_handleAppStateChange(state) {
    if (state == "background") {
        Reconnect();
    }
}


It may help to fix , I don't know about how to use in  ur code
